// 37_BytecodeInspection.java
public class BytecodeInspection {
    public void sampleMethod() {
        int a = 5;
        int b = 10;
        int c = a + b;
        System.out.println("Sum: " + c);
    }
    
    public static void main(String[] args) {
        new BytecodeInspection().sampleMethod();
    }
}

/*
After compiling this file, run the command:
   javap -c BytecodeInspection
to inspect the generated bytecode.
*/
